### ISSUE TITLE
Geluiden werken nu wel, ook op o-schijf, robuust?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-lexical-decision#16]
Ik had in de documentatie voor m'n studenten staan: 

_Note if your experiment template involves audio: when running the experiment on your own computer or on the O-drive, you will get the error ‘Experiment failed to load’. (The cause of this error is that your browser will block the loading of the audio stimuli from your own disks; this is a security measure to protect your computer from attacks from websites). To fix this, you can use a browser extensions that runs  a local web server on your own computer, for instance this one: 
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb
It’s very easy to set up and run, instructions are here:
https://www.simplehelp.net/2021/07/09/how-to-run-a-basic-web-server-with-google-chrome/_

Maar bij dit experiment doen alle geluiden het gewoon, zowel lokaal als op de o-schijf. Dat is heel fijn natuurlijk, maar is het ook robuust? Dwz kan ik de waarschuwing en oplossing hierboven uit de documentatie halen?

**Comment by maartenuni** [comment]
This  has someting with CORS to do, perhaps @bbonf  know a little more about this. I can see in the browser console, that the current implementation of jspsych detects that is is running the file:// protocol and perhaps it tries to work around cors issues.

**Comment by bbonf** [comment]
I'm not 100% sure but I think you're right in that jsPsych has a fallback audio playback mechanism (possibly HTML5 audio element instead of Web Audio API). Running a local server is beneficial because that would give the most similar result to running on the real server, but it perhaps isn't necessary when just setting the experiment up for the first time.

On an unrelated note, I don't get any audio playback for the practice items, only the trial ones.

**Comment by maartenuni** [comment]
> On an unrelated note, I don't get any audio playback for the practice items, only the trial ones.

I've turned the jspsych lexical decision experiments, from 6  experiments with one flavour, in one experiment that supports all flavors. In the stimuli.js, you can specify which stimuli you want to present eg. `visual_prime` vs `auditory_target` If you don't specify them you don't get them. It happens to be that no auditory target nor primes were selected in the practice phase, hence current behavior (no sounds in the practice phase) is desired given the stimuli for the practice items.

I;ve tried to compose a set of items that demonstrates forward vs backward masking, auditory vs visual stimuli and trials with and without masking. But I think we've 2 * 2 * 2 * 2 possible combination, although it probably doesn't make sense to have a visual backward mask for a auditory prime. Creating a list with all permutations was in my opinion a bit to elaborate.

**Comment by bbonf** [comment]
Right, this makes sense, I forgot about that

**Comment by maartenuni** [comment]
But to conclude, I would say, the students should be able to skip running a server and jspsych will do the right thing in the backend. If it doesn't work on their pc/laptop, they can stil run a server, and once the experiment is on the experiment-server, the problem is gone anyway.
is this clear @irisopgithub ?

**Comment by irisopgithub** [comment]
excellent, thank you both very much!
